services:
  bot-outer_test:
    env_file: ./.env_test
    container_name: favr_outer_test
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env_outer
    command:
      python3 get_bot.py --Mode outer
    volumes:
      - embeddings_outer:/app/db_citizens/
      - whisper:/root/.cache/whisper/

volumes:
  embeddings_outer:
  whisper:
