services:
  bot-inner:
    container_name: favr_bot_inner
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env_inner
    environment:
      MODE: "inner"
    command: 
      python3 get_bot.py --Mode inner
    volumes:
      - embeddings_inner:/app/db/
      - whisper:/root/.cache/whisper/
      - inner_logs:/app/logs/
      - docs_to_send:/app/documents_to_send/
  bot-outer:
    container_name: favr_bot_outer
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env_outer
    environment:
      MODE: "outer"
    command:
      python3 get_bot.py --Mode outer
    volumes:
      - embeddings_outer:/app/db_citizens/
      - whisper:/root/.cache/whisper/
      - outer_logs:/app/logs/


volumes:
  embeddings_inner:
  embeddings_outer:
  whisper:
  outer_logs:
  inner_logs:
  docs_to_send:

