services:
  bot-outer:
    container_name: favr_bot_outer
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      MODE: "outer"
    command:
      python3 /app/bot/get_bot.py --Mode outer
    volumes:
      - embeddings_outer:/app/bot/db_citizens/
      - outer_logs:/app/logs/
      - user_db_outer:/user_db/
      - local_models:/tmp/llama_index/


volumes:
  embeddings_outer:
  outer_logs:
  send_to_list:
  user_db_outer:
  local_models:

