services:
  bot-outer_test:
    env_file: ./.env_test
    environment:
      MODE: "inner"
    container_name: favr_outer_test
    build:
      context: .
      dockerfile: Dockerfile
    command:
      python3 /app/bot/get_bot.py --Mode inner
    volumes:
      - embeddings_outer:/app/bot/db_citizens/
      - whisper:/root/.cache/whisper/
      - test_logs:/app/logs/
      - send_to_list_test:/app/bot/send_to/
      - docs_to_send_test:/app/bot/documents_to_send/
      - docs_sent_test:/app/bot/documents_sent/
      - user_db_test:/user_db/

volumes:
  embeddings_outer:
  whisper:
  test_logs:
  send_to_list_test:
  docs_to_send_test:
  docs_sent_test:
  user_db_test:
