version: '3.8'
services:
  bot-outer:
    container_name: favr_outer_test
    build: .
    command: >
      sh -c "python3 get_bot.py --Mode outer"
    volumes:
      - embeddings_outer:/app/db_citizens/
      - whisper:/app/services/models/

volumes:
  embeddings_outer:
  whisper: