version: '3.8'
services:
  bot-outer:
    env_file: ./.env_test
    container_name: favr_outer_test
    build: .
    command:
      python3 get_bot.py --Mode outer
    volumes:
      - embeddings_outer:/app/db_citizens/

volumes:
  embeddings_outer:
