services:
  bot-inner:
    container_name: favr_bot_inner
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env_inner
    environment:
      MODE: "inner"
      SBER_SPEECH_API_KEY: "KEY"
      CREDENTIALS_NONRAG: "KEY"
    command: 
      python3 /app/bot/get_bot.py --Mode inner
    volumes:
      - embeddings_inner:/app/bot/db/
      - inner_logs:/app/logs/
      - docs_to_send:/app/documents_to_send/
      - docs_sent:/app/documents_sent/
      - send_to_list:/app/send_to/
      - user_db_inner:/user_db/
      - local_models:/tmp/llama_index/
      - whisper:/app/bot/services/models/


volumes:
  embeddings_inner:
  inner_logs:
  docs_to_send:
  docs_sent:
  send_to_list:
  user_db_inner:
  local_models:
  whisper:

